// Package docs generates the reference pages that must never drift from the
// code: one page per rule from the presets, and the CEL reference from the
// environment. `fleetlint docs --check` fails when the pages in the output
// directory differ; the documentation repository runs it.
package docs

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/fleetlint/fleetlint/internal/catalog"
	"github.com/fleetlint/fleetlint/internal/celenv"
	"github.com/fleetlint/fleetlint/internal/model"
)

// Page is a generated file, path relative to the docs directory.
type Page struct {
	Path    string
	Content []byte
}

// Options adapt the generated pages to where they are published.
type Options struct {
	// IndexFile names the rule index inside rules/ (README.md for a plain
	// directory, _index.md for a Hugo section).
	IndexFile string
}

// Generate renders every generated page. Each page ends with the catalog
// version it describes, because rules are versioned apart from the tool.
func Generate(opts Options) ([]Page, error) {
	if opts.IndexFile == "" {
		opts.IndexFile = "README.md"
	}
	rules, byPreset, err := loadPresets()
	if err != nil {
		return nil, err
	}
	pages := []Page{
		{Path: "rules/" + opts.IndexFile, Content: rulesIndex(rules, byPreset)},
		{Path: "cel-reference.md", Content: celReference()},
	}
	for _, r := range rules {
		pages = append(pages, Page{Path: "rules/" + strings.ReplaceAll(r.ID, "/", "--") + ".md", Content: rulePage(r)})
	}
	footer := []byte("\n---\n\nGenerated by `fleetlint docs` from catalog " + catalog.ModuleVersion() + ".\n")
	for i := range pages {
		pages[i].Content = append(bytes.TrimRight(pages[i].Content, "\n"), append([]byte("\n"), footer...)...)
	}
	return pages, nil
}

// prose makes catalog text safe as Markdown prose: outside code spans, an
// angle bracket is text (`<digest>`, `<name>`), not the start of an HTML tag
// that a renderer would drop.
func prose(text string) string {
	parts := strings.Split(text, "`")
	for i := 0; i < len(parts); i += 2 {
		parts[i] = strings.NewReplacer("<", "&lt;", ">", "&gt;").Replace(parts[i])
	}
	return strings.Join(parts, "`")
}

// refLinks writes URLs so that Markdown renders them as links.
func refLinks(refs []string) []string {
	links := make([]string, 0, len(refs))
	for _, ref := range refs {
		if strings.HasPrefix(ref, "https://") {
			ref = "<" + ref + ">"
		}
		links = append(links, ref)
	}
	return links
}

func loadPresets() ([]model.Rule, map[string][]string, error) {
	seen := map[string]model.Rule{}
	byPreset := map[string][]string{}
	for _, name := range catalog.Presets() {
		cats, err := catalog.Loader{}.Load("fleetlint:" + name)
		if err != nil {
			return nil, nil, err
		}
		own := cats[len(cats)-1]
		for _, r := range own.Rules {
			seen[r.ID] = r
			byPreset[name] = append(byPreset[name], r.ID)
		}
	}
	rules := make([]model.Rule, 0, len(seen))
	for _, r := range seen {
		rules = append(rules, r)
	}
	sort.Slice(rules, func(i, j int) bool { return rules[i].ID < rules[j].ID })
	return rules, byPreset, nil
}

func rulesIndex(rules []model.Rule, byPreset map[string][]string) []byte {
	var b bytes.Buffer
	b.WriteString("# Rule reference\n\nGenerated by `fleetlint docs`; do not edit. One page per rule shipped in the presets.\n\n")
	b.WriteString("| Rule | Severity | Tiers | Stacks | Scope | Preset |\n|---|---|---|---|---|---|\n")
	presetOf := map[string]string{}
	for p, ids := range byPreset {
		for _, id := range ids {
			presetOf[id] = p
		}
	}
	for _, r := range rules {
		fmt.Fprintf(&b, "| [%s](%s.md) | %s | %s | %s | %s | %s |\n",
			r.ID, strings.ReplaceAll(r.ID, "/", "--"), r.Severity, tiers(r), stacks(r), scope(r), presetOf[r.ID])
	}
	return b.Bytes()
}

// writeOriginRows adds the rows that depend on how the rule was taken in.
func writeOriginRows(b *bytes.Buffer, r model.Rule) {
	if r.SelectedBy != "" {
		fmt.Fprintf(b, "| Selected by | %s |\n", r.SelectedBy)
	}
	if r.Locked || r.MinSeverity != "" || !r.ExceptionsAllowed() {
		fmt.Fprintf(b, "| Policy | locked: %t, floor: %s, exceptions: %t |\n", r.Locked, r.Floor(), r.ExceptionsAllowed())
	}
}

func rulePage(r model.Rule) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n%s\n\n", r.ID, prose(r.Title))
	fmt.Fprintf(&b, "| | |\n|---|---|\n| Severity | %s |\n| Tiers | %s |\n| Stacks | %s |\n| Scope | %s |\n| Kind | %s |\n| Source | %s |\n",
		r.Severity, tiers(r), stacks(r), scope(r), r.Kind, r.Source)
	writeOriginRows(&b, r)
	b.WriteString("\n")
	fmt.Fprintf(&b, "## Requirement\n\n%s\n\n", prose(strings.TrimSpace(r.Requirement)))
	if r.Rationale != "" {
		fmt.Fprintf(&b, "## Why\n\n%s\n\n", prose(strings.TrimSpace(r.Rationale)))
	}
	if r.When != "" {
		fmt.Fprintf(&b, "## Applies when\n\n```cel\n%s\n```\n\n", strings.TrimSpace(r.When))
	}
	if r.Expr != "" {
		b.WriteString("## Check\n\n")
		if r.Foreach != "" {
			fmt.Fprintf(&b, "For each `item` in:\n\n```cel\n%s\n```\n\n", strings.TrimSpace(r.Foreach))
		}
		fmt.Fprintf(&b, "```cel\n%s\n```\n\n", strings.TrimSpace(r.Expr))
	}
	if len(r.Params) > 0 {
		b.WriteString("## Parameters\n\n")
		keys := make([]string, 0, len(r.Params))
		for k := range r.Params {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(&b, "- `%s`: `%v`\n", k, r.Params[k])
		}
		b.WriteString("\n")
	}
	fmt.Fprintf(&b, "## Fix\n\n%s\n\n", prose(r.Fix.Human))
	if r.Fix.Agent != "" {
		fmt.Fprintf(&b, "Agent instruction: %s\n\n", prose(r.Fix.Agent))
	}
	if len(r.Fix.Actions) > 0 {
		fmt.Fprintf(&b, "`fleetlint fix` can apply this rule's fix automatically (%d action(s)).\n\n", len(r.Fix.Actions))
	}
	if len(r.Refs) > 0 {
		fmt.Fprintf(&b, "See: %s\n", strings.Join(refLinks(r.Refs), ", "))
	}
	// Exactly one trailing newline, whichever section came last.
	return append(bytes.TrimRight(b.Bytes(), "\n"), '\n')
}

func celReference() []byte {
	var b bytes.Buffer
	b.WriteString("# CEL reference\n\nGenerated by `fleetlint docs`; do not edit. Everything an `expr` rule can use.\n\n## Variables\n\n| Variable | Contents |\n|---|---|\n")
	for _, v := range celenv.Variables {
		fmt.Fprintf(&b, "| `%s` | %s |\n", v.Signature, v.Doc)
	}
	b.WriteString("\n## Functions\n\n| Function | Returns |\n|---|---|\n")
	for _, a := range celenv.Accessors {
		fmt.Fprintf(&b, "| `%s` | %s |\n", a.Signature, a.Doc)
	}
	b.WriteString("\nStandard CEL operators, macros (`all`, `exists`, `filter`, `map`, `has`) and string functions (`contains`, `startsWith`, `endsWith`, `matches`, `size`) are available. A rule's result must be a bool; with `foreach`, the list expression is evaluated first and `expr` once per `item`.\n")
	return b.Bytes()
}

func tiers(r model.Rule) string {
	if len(r.Tiers) == 0 {
		return "all"
	}
	parts := make([]string, 0, len(r.Tiers))
	for _, t := range r.Tiers {
		parts = append(parts, fmt.Sprint(t))
	}
	return strings.Join(parts, ", ")
}

func stacks(r model.Rule) string {
	if len(r.Stacks) == 0 {
		return "any"
	}
	return strings.Join(r.Stacks, ", ")
}

func scope(r model.Rule) string {
	if r.Scope == "" {
		return string(model.ScopeEach)
	}
	return string(r.Scope)
}
